version: '3.8'

services:
  books-api:
    container_name: angular_frontend_page
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
    networks:
      - default
    volumes:
      - ./books-api:/usr/src/app/books-api
    restart: always

networks:
  nesjs-network:
